# Generated by Django 5.0.7 on 2025-07-24 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('shop_app', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop_app.shop'),
            preserve_default=False,
        ),
    ]
