# Generated by Django 5.0.7 on 2025-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_remove_category_owner_category_shop'),
        ('shop_app', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('nom', 'shop')},
        ),
    ]
