# Generated by Django 5.0.7 on 2025-07-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_category_nom_alter_category_unique_together'),
        ('shop_app', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.category'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nom', 'shop')},
        ),
    ]
