# Generated by Django 5.0.7 on 2025-07-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_options_alter_product_category_and_more'),
        ('shop_app', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='shop',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='shop_app.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panier',
            name='shop',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='shop_app.shop'),
            preserve_default=False,
        ),
    ]
