# Generated by Django 5.0.7 on 2025-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_receive_notifications_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
